server:
  port: 8080

spring:
  application:
    name: multi-service-app

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: INFO

task-service:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

user-service:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
