server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  flyway:
    baseline-on-migrate: true  # Aqui é onde deve estar a configuração Flyway

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true

debug: true
