server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  flyway:
    baseline-on-migrate: true

feign:
  client:
    config:
      default:
        loggerLevel: full

  notification-service:
    url: http://localhost:8082

debug: true

---

server:
  port: 8083

spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  flyway:
    baseline-on-migrate: true

feign:
  client:
    config:
      default:
        loggerLevel: full

  user-service:
    url: http://localhost:8081  # URL para o user-service

debug: true

